name: Deploy Laravel to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🛠️ Install NPM dependencies & Build Assets
        run: |
          npm install
          npm run build --if-present

      - name: 📂 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql, zip

      - name: 📦 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🚀 Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/ # Sesuaikan folder root hosting Anda (misal public_html/ atau subfolder)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env.example
            phpunit.xml
            README.md
            vite.config.js
            tailwind.config.js
            package.json
            package-lock.json
